#!/usr/bin/env bash
#configure nginx server to listen at port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#to restart nginx 
service nginx restart
