#!/usr/bin/env bash
#This script wil display "Best School" 10 times, except for the 9th iteration where it displays
#Best School and then Hi on a new line

i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]; then
	   echo "Hi"
	fi
	((i++))
done
